# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-02-23 14:40+0100\n"
"PO-Revision-Date: 2021-12-24 14:33+0100\n"
"Last-Translator: Stéphane Diemer <stephane.diemer@ubicast.eu>\n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Poedit 2.2.1\n"

# Translated by DeepL.
#: admin_utils.py:14
msgid "Export selected objects as CSV file"
msgstr "Exportar los objetos seleccionados como archivo CSV"

#: admin_utils.py:112
msgid "CSV export"
msgstr "Exportación a CSV"

# Translated by DeepL.
#: antivirus_utils.py:49
msgid "Your request was reported and if you send again infected files, you will be banned."
msgstr "Tu solicitud ha sido denunciada y si vuelves a enviar archivos infectados, serás expulsado."

# Translated by DeepL.
#: antivirus_utils.py:50
msgid "Failed to run antivirus scanner."
msgstr "No se ha podido ejecutar el escáner antivirus."

# Translated by DeepL.
#: antivirus_utils.py:51
msgid "Cannot scan file because it does not exist."
msgstr "No se puede escanear el archivo porque no existe."

# Translated by DeepL.
#: antivirus_utils.py:52
msgid "Your file was rejected because it is infected."
msgstr "Su archivo fue rechazado porque está infectado."

# Translated by DeepL.
#: antivirus_utils.py:53
msgid "Cannot scan file because it is not a file."
msgstr "No se puede escanear el archivo porque no es un archivo."

# Translated by DeepL.
#: antivirus_utils.py:54
msgid "Cannot scan file because it is neither a file nor a directory."
msgstr "No se puede escanear el archivo porque no es ni un archivo ni un directorio."

# Translated by DeepL.
#: antivirus_utils.py:55
msgid "Failed to scan your file with the antivirus."
msgstr "No se ha podido escanear el archivo con el antivirus."

#: auth_utils.py:42
msgid "Your account is disabled."
msgstr "Tu cuenta está inhabilitada."

# Translated by DeepL.
#: auth_utils.py:44
msgid "Your username and password do not match."
msgstr "Su nombre de usuario y contraseña no coinciden."

# Translated by DeepL.
#: auth_utils.py:46
msgid "Authentication required."
msgstr "Se requiere autentificación."

# Translated by DeepL.
#: auth_utils.py:49
msgid "Access authentication"
msgstr "Autenticación de acceso"

# Translated by DeepL.
#: auth_utils.py:85 auth_utils.py:90
msgid "The password must contain at least 3 types of characters (types are lower case letters, upper case letters, digits and special characters)."
msgstr "La contraseña debe contener al menos 3 tipos de caracteres (los tipos son letras minúsculas, letras mayúsculas, dígitos y caracteres especiales)."

#: files_utils.py:40
msgid "B"
msgstr "B"

#: files_utils.py:44
msgid "kB"
msgstr "kB"

#: files_utils.py:48
msgid "MB"
msgstr "MB"

#: files_utils.py:52
msgid "GB"
msgstr "GB"

#: files_utils.py:55
msgid "TB"
msgstr "TB"

#: forms_utils.py:121
msgid "Yes"
msgstr "Sí"

# Translated by DeepL.
#: forms_utils.py:123
msgid "No"
msgstr "No"

# Translated by DeepL.
#: json_utils.py:91
msgid "Invalid request method"
msgstr "Método de solicitud no válido"

#: json_utils.py:96
msgid "Authentication required"
msgstr "Se requiere autenticación"

#: json_utils.py:127
msgid "Access denied"
msgstr "Acceso denegado"

# Translated by DeepL.
#: json_utils.py:129
msgid "Page not found"
msgstr "Página no encontrada"

# Translated by DeepL.
#: json_utils.py:134
msgid "Infected file detected"
msgstr "Archivo infectado detectado"

# Translated by DeepL.
#: json_utils.py:139
msgid "Internal server error"
msgstr "Error interno del servidor"

# Translated by DeepL.
#: ldap_utils.py:76
msgid "Error when initializing connection with LDAP server."
msgstr "Error al inicializar la conexión con el servidor LDAP."

#: ldap_utils.py:76 ldap_utils.py:104 ldap_utils.py:131 ldap_utils.py:282
msgid "Error:"
msgstr "Error:"

# Translated by DeepL.
#: ldap_utils.py:104
msgid "Error when trying to authenticate on LDAP server."
msgstr "Error al intentar autenticarse en el servidor LDAP."

# Translated by DeepL.
#: ldap_utils.py:130
msgid "Search on LDAP server failed."
msgstr "La búsqueda en el servidor LDAP ha fallado."

# Translated by DeepL.
#: ldap_utils.py:133
msgid "Arguments:"
msgstr "Argumentos:"

#: ldap_utils.py:167
msgid "User not found."
msgstr "Usuario no encontrado."

# Translated by DeepL.
#: ldap_utils.py:179
msgid "Group not found."
msgstr "Grupo no encontrado."

# Translated by DeepL.
#: ldap_utils.py:282
msgid "Error when trying to get user information."
msgstr "Error al intentar obtener la información del usuario."

# Translated by DeepL.
#: ldap_utils.py:291
msgid "Login failed (however the user exists in LDAP)."
msgstr "El inicio de sesión falló (sin embargo, el usuario existe en LDAP)."

# Translated by DeepL.
#: ldap_utils.py:293
msgid "Login succeeded."
msgstr "El inicio de sesión fue exitoso."

# Translated by DeepL.
#: ldap_utils.py:294
#, python-format
msgid "User \"%s\" data:"
msgstr "Datos del usuario \"%s\":"

# Translated by DeepL.
#: ldap_utils.py:299
msgid "User groups:"
msgstr "Grupos de usuarios:"

# Translated by DeepL.
#: ldap_utils.py:304
msgid "Error when trying to get groups."
msgstr "Error al intentar obtener grupos."

# Translated by DeepL.
#: ldap_utils.py:315
msgid "No groups found."
msgstr "No se han encontrado grupos."

# Translated by DeepL.
#: settings_utils.py:36
msgid "Failed to backup settings:"
msgstr "Fallo en la copia de seguridad de la configuración:"

#: settings_utils.py:74
msgid "No changes to save."
msgstr "Ningún cambio que guardar."

# Translated by DeepL.
#: settings_utils.py:83 settings_utils.py:143
msgid "Your changes were not saved but were applied to the running software."
msgstr "Sus cambios no se han guardado, pero se han aplicado al software en funcionamiento."

# Translated by DeepL.
#: settings_utils.py:120 settings_utils.py:172
msgid "Unable to write configuration file:"
msgstr "No se puede escribir el archivo de configuración:"

# Translated by DeepL.
#: settings_utils.py:121 settings_utils.py:173
msgid "Your changes will be active after the service restart."
msgstr "Sus cambios se activarán tras el reinicio del servicio."

# Translated by DeepL.
#: settings_utils.py:123 settings_utils.py:175
msgid "The service will be restarted in 2 seconds."
msgstr "El servicio se reiniciará en 2 segundos."

# Translated by DeepL.
#: system_utils.py:99
msgid "Password required."
msgstr "Se requiere una contraseña."

# Translated by DeepL.
#: system_utils.py:108
#, python-format
msgid "Command exited with code %s."
msgstr "El comando salió con el código %s."

# Translated by DeepL.
#: system_utils.py:139 system_utils.py:141 system_utils.py:148
#: system_utils.py:169
msgid "Unable to write file."
msgstr "No se puede escribir el archivo."

# Translated by DeepL.
#: system_utils.py:139
msgid "Specified path is a directory."
msgstr "La ruta especificada es un directorio."

# Translated by DeepL.
#: system_utils.py:141
msgid "Invalid file path."
msgstr "Ruta de archivo no válida."

# Translated by DeepL.
#: system_utils.py:154
msgid "You need to send the main password to edit this file."
msgstr "Es necesario enviar la contraseña principal para editar este archivo."

# Translated by DeepL.
#: system_utils.py:163
#, python-format
msgid "Unable to create temporary file \"%s\"."
msgstr "No se ha podido crear el archivo temporal \"%s\"."

# Translated by DeepL.
#: system_utils.py:170
msgid "File updated."
msgstr "Archivo actualizado."

#: templates/forms_utils/password_toggle_input.html:5
msgid "Hide value"
msgstr "Ocultar valor"

#: templates/forms_utils/password_toggle_input.html:5
#: templates/forms_utils/password_toggle_input.html:7
msgid "Edit value"
msgstr "Editar valor"
